CREATE TABLE ITEMS(
ID BIGINT PRIMARY KEY,
NAME VARCHAR(128),
DESCRIPTION VARCHAR(512),
TYPE SMALLINT,
CONTENT CLOB,
READ_COUNT SMALLINT,
CREATE_TIME TIMESTAMP,
UPDATE_TIME TIMESTAMP,
PARENT BIGINT
);

CREATE TABLE TAGS(
ID BIGINT PRIMARY KEY,
NAME VARCHAR(128),
CREATE_TIME TIMESTAMP
);